# Generated by Django 3.1 on 2020-08-15 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='novels',
            new_name='Story',
        ),
    ]
